package com.roudikk.common.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF974166)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffd9e6)
val md_theme_light_onPrimaryContainer = Color(0xFF3e0020)
val md_theme_light_secondary = Color(0xFF735760)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffd9e4)
val md_theme_light_onSecondaryContainer = Color(0xFF2a151d)
val md_theme_light_tertiary = Color(0xFF7d5636)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdcc2)
val md_theme_light_onTertiaryContainer = Color(0xFF2f1400)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a1c)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a1c)
val md_theme_light_surfaceVariant = Color(0xFFf2dde2)
val md_theme_light_onSurfaceVariant = Color(0xFF514347)
val md_theme_light_outline = Color(0xFF827377)
val md_theme_light_inverseOnSurface = Color(0xFFfaeef0)
val md_theme_light_inverseSurface = Color(0xFF352f30)
val md_theme_light_inversePrimary = Color(0xFFffb0ce)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb0ce)
val md_theme_dark_onPrimary = Color(0xFF5d1137)
val md_theme_dark_primaryContainer = Color(0xFF7a294e)
val md_theme_dark_onPrimaryContainer = Color(0xFFffd9e6)
val md_theme_dark_secondary = Color(0xFFe2bdc8)
val md_theme_dark_onSecondary = Color(0xFF422932)
val md_theme_dark_secondaryContainer = Color(0xFF5a3f48)
val md_theme_dark_onSecondaryContainer = Color(0xFFffd9e4)
val md_theme_dark_tertiary = Color(0xFFf0bc96)
val md_theme_dark_onTertiary = Color(0xFF49290e)
val md_theme_dark_tertiaryContainer = Color(0xFF633f21)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdcc2)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a1c)
val md_theme_dark_onBackground = Color(0xFFebdfe1)
val md_theme_dark_surface = Color(0xFF201a1c)
val md_theme_dark_onSurface = Color(0xFFebdfe1)
val md_theme_dark_surfaceVariant = Color(0xFF514347)
val md_theme_dark_onSurfaceVariant = Color(0xFFd5c1c6)
val md_theme_dark_outline = Color(0xFF9e8c91)
val md_theme_dark_inverseOnSurface = Color(0xFF201a1c)
val md_theme_dark_inverseSurface = Color(0xFFebdfe1)
val md_theme_dark_inversePrimary = Color(0xFF974166)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF853859)
val error = Color(0xFFba1b1b)